### PR TITLE
Support Swift 5

### LINKED ISSUE #200: Update to support Swift 5
Title has it. Update the pods and make this framework support Swift 5 standards.

- [x] update pods to Swift 5 compatible versions
- [x] ensure tools are compatible (Circle CI tests pass)

### PR DESCRIPTION
**Pull request by mindgraffiti**
Closes #200.

This PR:
1. Updates pods to support Swift 5
2. Make Xcode recommended changes to support Swift 5
3. Updates the project file to remove a warning.

Changes made by Platform 9 3/4: updated tooling to support Xcode 10.2 and Swift 5 🌟 

First reviewer wins! 🏆 

## To test
- `bundle exec pod install` ensure no warnings are spit out in the command line
- build the framework
- run the unit tests
- no warnings should appear in Xcode

## To test in a host app
- check out this PR for WCiOS as the host app: https://github.com/woocommerce/woocommerce-ios/pull/924
- `bundle exec pod install`. No warnings should appear in the command line.
- run unit tests
- run app

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@mindgraffiti - Just a note to point out tests seem to be failing due to the Swift version change.

**Comment by mindgraffiti** [comment]
Sorry about the early request to review. It's not ready yet.

**Comment by mindgraffiti** [comment]
I disabled my Chrome Javascript blocker. It's doing weird things when I request reviewers.

**Comment by mindgraffiti** [comment]
Thanks @astralbodies!

**Pull request merged**
