### PR TITLE
Improved the device identification methods.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Shared/issues/56).

@bummytime - Can you test this on iPhone 6+?
@SergioEstevao - Can you test this on iPhone 6?

PS: use the example app, option "Device identification"

### CODE REVIEW

**Comment by bummytime** [comment]
Very nice little upgrade @diegoreymendez. It works on the 6+ in both scaled:

screen shot 2015-02-18 at 2 40 22 pm

and unscaled mode:

screen shot 2015-02-18 at 2 42 39 pm

The sim seems to work as well. Assuming @SergioEstevao gives a thumbs up for the iPhone 6, this would be a :shipit: from me.

**Comment by diegoreymendez** [comment]
@bummytime - Uploaded some changes to fix the device identification code for the simulator as well.

**Comment by bummytime** [comment]
@diegoreymendez Just tested your updates in the Shared example app as well as the Editor example app. Everything worked great (iPhone Sim + iPhone 6+ device).

I say :shipit:

**Comment by SergioEstevao** [comment]
It also works on the iPhone 6.

**Comment by diegoreymendez** [comment]
Thank you @SergioEstevao and @bummytime.

**Pull request merged**
